[phases.setup]
nixPkgs = ["nodejs_18", "python3", "python3Packages.pip", "gcc"]

[phases.install]
cmds = [
    "npm install --legacy-peer-deps", 
    "pip3 install -r requirements.txt"
]

[start]
cmd = "npm start"