[phases.setup]
nixPkgs = ["nodejs_18", "python3", "python3Packages.pip", "gcc"]

[phases.install]
cmds = [
    "npm install --legacy-peer-deps",
    "python3 -m venv .venv",
    ".venv/bin/pip install -r requirements.txt"
]

[start]
cmd = ". .venv/bin/activate && npm start"